services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    environment: 
      - WHATSAPP_WEBHOOK=${WHATSAPP_WEBHOOK}
      - WHATSAPP_WEBHOOK_SECRET=${WHATSAPP_WEBHOOK_SECRET}
    restart: always
    ports:
      - "3080"
    volumes:
      - whatsapp:/app/storages
    command:
      - rest
      - --basic-auth=${WA_USER}:${WA_PASSWORD}
      - --port=3080
      - --debug=true
      - --os=Chrome
      - --account-validation=false

volumes:
  whatsapp:

